//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventEntities : DbContext
    {
        public EventEntities()
            : base("name=EventEntities")
        {
            Utility.ConfigureConnectionString(this);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<TemporaryCard> TemporaryCards { get; set; }
        public virtual DbSet<SpecialCard> SpecialCards { get; set; }
        public virtual DbSet<MediaCard> MediaCards { get; set; }
        public virtual DbSet<VipCard> VipCards { get; set; }
    }
}
