//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string Role { get; set; }
        public string Organization { get; set; }
        public string Level { get; set; }
        public string Prefix { get; set; }
    }
}
