//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialCard
    {
        public int ID { get; set; }
        public string Uid { get; set; }
        public string Level { get; set; }
    }
}
